import { chromium } from 'playwright'

function escapeHtml(str) {
  return String(str ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]))
}

const STATUS_LABEL = { pass: 'Pass', fail: 'Fail', 'not-tested': 'Not tested' }

function renderIssueRow(issue) {
  return `<tr>
    <td>${escapeHtml(issue.title)}</td>
    <td>${escapeHtml(issue.wcagCriterion || '—')}</td>
    <td>${escapeHtml(issue.severity)}</td>
    <td>${escapeHtml(issue.plainExplanation)}</td>
    <td>${escapeHtml(issue.howToFix)}</td>
  </tr>`
}

function renderCriterionRow(c) {
  return `<tr>
    <td>${escapeHtml(c.id)}</td>
    <td>${escapeHtml(c.name)}</td>
    <td class="status-${escapeHtml(c.status)}">${escapeHtml(STATUS_LABEL[c.status] || c.status)}</td>
    <td>${escapeHtml(c.explanation || '')}</td>
  </tr>`
}

function buildHtml(scan) {
  const free = scan.aiFreeSummary || {}
  const full = scan.aiFullReport
  const generatedAt = new Date().toISOString().slice(0, 10)

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<style>
  body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #1e293b; padding: 32px; }
  h1 { font-size: 20px; margin-bottom: 4px; }
  h2 { font-size: 15px; margin-top: 28px; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; }
  .meta { color: #64748b; font-size: 12px; margin-bottom: 16px; }
  .score { font-size: 40px; font-weight: bold; }
  .score-label { color: #16a34a; font-weight: 600; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 11px; }
  th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid #eef2f7; vertical-align: top; }
  th { background: #f8fafc; }
  .status-pass { color: #16a34a; font-weight: 600; }
  .status-fail { color: #dc2626; font-weight: 600; }
  .status-not-tested { color: #94a3b8; }
  .disclaimer { margin-top: 32px; font-size: 10px; color: #94a3b8; }
  .statement { white-space: pre-line; font-size: 11px; background: #f8fafc; padding: 12px; border-radius: 6px; }
</style>
</head>
<body>
  <h1>EAAChecker — Accessibility Report</h1>
  <div class="meta">${escapeHtml(scan.url)} &middot; generated ${generatedAt}</div>

  <div class="score">${scan.score ?? '—'}<span style="font-size:16px;color:#94a3b8;"> / 100</span></div>
  <p>${escapeHtml(free.plainLanguageSummary || '')}</p>

  <h2>Top issues</h2>
  <table>
    <thead><tr><th>Issue</th><th>WCAG</th><th>Severity</th><th>Explanation</th><th>How to fix</th></tr></thead>
    <tbody>${(free.topIssues || []).map(renderIssueRow).join('') || '<tr><td colspan="5">No critical issues found.</td></tr>'}</tbody>
  </table>

  ${
    full
      ? `<h2>Full WCAG 2.1 AA criteria</h2>
  <table>
    <thead><tr><th>ID</th><th>Criterion</th><th>Status</th><th>Notes</th></tr></thead>
    <tbody>${(full.criteria || []).map(renderCriterionRow).join('')}</tbody>
  </table>

  <h2>Accessibility statement draft</h2>
  <div class="statement">${escapeHtml(full.accessibilityStatementDraft || '')}</div>`
      : ''
  }

  <p class="disclaimer">
    This report is generated by an automated scan (axe-core + Lighthouse, summarized by AI) and is
    informational only. It is not a legal compliance certification or guarantee of EAA/WCAG conformance.
  </p>
</body>
</html>`
}

export async function generateReportPdf(scan) {
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox', '--disable-dev-shm-usage'] })
  try {
    const page = await browser.newPage()
    await page.setContent(buildHtml(scan), { waitUntil: 'load' })
    return await page.pdf({ format: 'A4', margin: { top: '20px', bottom: '20px', left: '20px', right: '20px' } })
  } finally {
    await browser.close().catch(() => {})
  }
}
